spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: ${SHOW_SQL:false}
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver